### ISSUE TITLE
大佬能不能教下编译。

### ISSUE THREAD

**Issue by hkthomas** [minoic/peo#1]
初学者不是很懂。编译爆了个这个错误。
文件没动，:)

GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build --ldflags="-s -w" -v -a -o dist/peo-linux-amd64 ./*.go
stat /home/thomas/peo-master/*.go: directory not found
make: *** [Makefile:38: linux-amd64] Error 1

**Comment by vlssu** [comment]
同求，没有看见任何编译教程，

**Comment by minoic** [comment]
已解决，请下载 [releases](https://github.com/minoic/peo/releases) 运行
