### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by XzaiCloud** [minoic/peo#10]
![image](https://user-images.githubusercontent.com/98635300/223824688-88c92271-a41e-4823-99b3-fefc3af678c7.png)

**Comment by XzaiCloud** [comment]
### 这是setting.conf内容
############################
#Please rename this file to settings.config after edited it
############################

############################
#Basic Settings
############################
# hostname to visit your web site
WebHostName = "s*.xzai.cloud"
 # use SSL or not
WebSecure = false
# website name to show
WebApplicationName = "MinoIC - PE"
 # website description to show
WebDescription = "Pterodactyl 服务器出售系统"
# website Admin address
WebAdminAddress = "ADMIN <admin@example.com>"

############################
#Pterodactyl Settings
############################
# your pterodactyl panel hostname
Serverhostname = "p*.xzai.cloud"
# wether your pterodactyl use SSL or not
Serversecure = false
# pterodactyl admin token
Serverpassword = "ptla_********LM6nq0HAhWA"

############################
#Database Settings
############################
# Choose database to use: MYSQL
Database = "MYSQL"
# salt
DatabaseSalt = "PEOSALT"
UseGormCache = true
SqlTablePrefix = "peo_"
#Fill the account info if database = "MYSQL"
MYSQLHost = "mysql:3306"
MYSQLUsername = "root"
MYSQLUserPassword = "****"
MYSQLDatabaseName = "peo"

############################
#SMTP settings
############################
# if set to false, we wont send any email to user
SMTPEnabled = false
SMTPHost = "smtpdm-ap-southeast-1.aliyun.com"
SMTPPort = 80
SMTPSendFrom = "ADMIN <admin@example.com>"
SMTPUsername = "admin@example.com"
SMTPUserPassword = "yourpassword"
SMTPLogo = ""
 #TLS/SSL
SMTPEncryption = "TLS"
#if DeleteEmailConfirm be set to true all admins will receive an email before Server being deleted
DeleteEmailConfirm = true

############################
#Cache Settings
############################
#change your cache settings
#CacheMode = "memory"/"file"/"redis"/"memcache"
CacheMode = "redis"
#CacheMode = "memory"
CacheMemoryGCInterval = 60
#CacheMode = "file"
CacheFilePath = "./cache"
CacheFileSuffix = ".cache"
CacheFileDirectoryLevel = "2"
CacheFileEmbedExpiry = "120"
#CacheMode = "redis"
CacheRedisKey = "collectionName"
CacheRedisCONN = "redis:6379"
CacheRedisdbNum = "0"
CacheRedisPassword = ""
#CacheMode = "memcache"
CacheMemcacheCONN = "127.0.0.1:11211"

############################
#Misc Settings
############################
# check if you want user to recharge balance
RechargeMode = false
# if set to false, we wont accept any discount
TotalDiscount = false
# Task run interval in seconds, 10 is recommended
AutoTaskInterval = 10
# fill if you want to enable alipay recharge
AliPayEnabled = false
AliPayPublicKey = ""
AliPayPrivateKey = ""
AliPayAppID = ""
# toggle album
AlbumEnabled = false

**Comment by XzaiCloud** [comment]
[settings.conf.txt](https://github.com/minoic/peo/files/10924449/settings.conf.txt)

**Comment by XzaiCloud** [comment]
> [settings.conf.txt](https://github.com/minoic/peo/files/10924449/settings.conf.txt)

这是配置文件

**Comment by minoic** [comment]
配置文件中这一行（39行）
MYSQLHost = "mysql:3306"
要改为实际的mysql地址，例如如果是本地部署则为localhost:3306
