### ISSUE TITLE
关于注册登录时出现的问题

### ISSUE THREAD

**Issue by ldeus** [minoic/peo#13]
首次注册时候出现：
注册失败！ XSRF 验证失败！
采用docker Compose 部署
![image](https://user-images.githubusercontent.com/48109470/228451909-e1896b33-95ff-452a-8171-16f6936b49aa.png)

**Comment by ldeus** [comment]
在手机、电脑等不同设备以及不同网络环境下均是这样，刷新也是如此。

**Comment by minoic** [comment]
是否修改过配置文件app.conf，使用的浏览器环境是？

**Comment by minoic** [comment]
我这边仅下载docker-compose.yml执行并在edge浏览器中未复现该问题

**Comment by ldeus** [comment]
> 是否修改过配置文件app.conf，使用的浏览器环境是？

没有改过配置文件，浏览器同为edge

**Comment by minoic** [comment]
检查了一下，目前问题是cookies的secure属性导致的，解决需要通过https访问，或等待下一个版本修复该问题

**Comment by ldeus** [comment]
> 检查了一下，目前问题是cookies的secure属性导致的，解决需要通过https访问，或等待下一个版本修复该问题

ok thanks
