### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by BiHServer** [minoic/peo#14]
I translated everything in /peo/views/*html to the German language when I run the command docker-compose up -d the page is online and everything works without problems, but it is still in the Chinese language.
Please help me to solve this problem.
Thank you

**Comment by minoic** [comment]
There are still some Chinese text in go files, so you can translate the Chinese text strings into German then build your own docker image with the Dockerfile, change the image in docker-compose.yml and use docker-compose up -d command.
Soon i will add translation modules thus every one can easily use their language, thanks for your comment.

**Comment by shee24** [comment]
Thanks for the answer, since I'm not an expert to be able to do it all, can you give me a little more detail on how to do it, if you can write me a few commands, I really like your system

**Comment by shee24** [comment]
Working Tanko You
