### ISSUE TITLE
测试后翼龙面板api无法删除

### ISSUE THREAD

**Issue by aopkcn** [minoic/peo#15]
搭建测试中情况如下：
0.2.1版本必须使用SSL证书才能进行注册，0.2.2说明中XSRF被移除，翼龙的面板中创建的API出现无法删除，最后在数据库中成功API,但是再次创建一个api不被使用又能正常删除，我不确定这是翼龙还是peo问题.

这么好的一个国内开源系统居然没人Fork真是瞎了眼

希望尽快开发出下载功能
添加用户列表控制页面
添加商品列表控制页面
添加订单列表控制页面

**Comment by minoic** [comment]
peo并没有锁定API禁止删除的功能，测试正在使用的api key也可以删除，推测应该是翼龙面板的一些限制或bug。
新页面会在i18n功能后陆续更新。
