### ISSUE TITLE
管理员注册后无法用户注册

### ISSUE THREAD

**Issue by aopkcn** [minoic/peo#17]
<html>
<body>
<div id="header" style="padding: 20px 10px; margin: 0px; background: rgb(255, 255, 221); border-bottom: 2px solid rgb(163, 21, 21); color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h2 style="padding: 0px; margin: 0px;">peo:Mail Error on Auth: 530 Username or passwd is NULL [@sm050103]</h2></div><div id="content" style="padding: 5px; margin: 0px; color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Request Method: | POST
-- | --
Request URL: | /reg
RemoteAddr: | 10.0.0.1

<div class="stack" style="padding: 0px; margin: 0px;"><b style="padding: 0px; margin: 0px; font-size: 13px; color: red;">Stack</b><pre style="padding: 0px 0px 0px 10px; margin: 0px;">/usr/local/go/src/runtime/panic.go:890
/workspace/internal/email/mail_manager.go:16
/workspace/internal/email/mail_confirm.go:43
/workspace/internal/controllers/reg_controller.go:101
/go/pkg/mod/github.com/beego/beego/v2@v2.0.7/server/web/router.go:1215
/go/pkg/mod/github.com/beego/beego/v2@v2.0.7/server/web/filter.go:83
/go/pkg/mod/github.com/beego/beego/v2@v2.0.7/server/web/router.go:1002
/usr/local/go/src/net/http/server.go:2936
/usr/local/go/src/net/http/server.go:1995
/usr/local/go/src/runtime/asm_amd64.s:1598
</pre></div></div><div id="footer" style="padding: 5px 10px; margin: 0px; border-top: 1px solid rgb(170, 170, 170); font-size: 12px; color: green; font-family: &quot;Microsoft YaHei&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="padding: 0px; margin: 0px;">beego 2.0.0 (beego framework)</p><p style="padding: 0px; margin: 0px;">golang version: go1.20.2</p></div>
</body>
</html>

**Comment by minoic** [comment]
请在管理员面板-设置中，关闭“邮件功能”，或填写具体的SMTP服务器信息
