### ISSUE TITLE
添加商品后无任何显示v0.2.4

### ISSUE THREAD

**Issue by aopkcn** [minoic/peo#21]
使用docker跑的，
1.进入数据库发现并没有写入商品数据，原先是可以写入的
2.邮箱验证返回502
3.填入支付宝密钥无法开启，停止docker后在配置文件中开启支付宝后无法启动容器

**Comment by aopkcn** [comment]
无法再进入后面的测试

**Comment by minoic** [comment]
1.添加完商品后检查页面底部是否出现红色错误提示
2.未复现请提供邮件和502页面截图
3.未复现请提供控制台报错截图

**Comment by aopkcn** [comment]
这是已经填写好支付宝密钥保存后，重新单独开启保存的日志
![image](https://github.com/minoic/peo/assets/45751694/8b16e583-fb46-45c4-9816-8a1659f258f5)
`PterodactylAPI returns: {"object":"list","data":[{"object":"node","attributes":{"id":1,"uuid":"5134e5c4-19ee-4c91-bea0-ecbd79ea5b3e","public":true,"name":"a.****.cn","description":null,"location_id":1,"fqdn":"a.****.cn","scheme":"https","behind_proxy":false,"maintenance_mode":false,"memory":102400,"memory_overallocate":0,"disk":184320,"disk_overallocate":0,"upload_size":1024,"daemon_listen":2,"daemon_sftp":3,"daemon_base":"\/var\/lib\/pterodactyl\/volumes","created_at":"2023-02-26T18:43:08+00:00","updated_at":"2023-05-25T00:51:21+00:00","allocated_resources":{"memory":9000,"disk":20480}}}],"meta":{"pagination":{"total":1,"count":1,"per_page":50,"current_page":1,"total_pages":1,"links":{}}}}PterodactylAPI returns: {"object":"list","data":[{"object":"node","attributes":{"id":1,"uuid":"5134e5c4-19ee-4c91-bea0-ecbd79ea5b3e","public":true,"name":"a.****.cn","description":null,"location_id":1,"fqdn":"a.****.cn","scheme":"https","behind_proxy":false,"maintenance_mode":false,"memory":102400,"memory_overallocate":0,"disk":184320,"disk_overallocate":0,"upload_size":1024,"daemon_listen":2,"daemon_sftp":3,"daemon_base":"\/var\/lib\/pterodactyl\/volumes","created_at":"2023-02-26T18:43:08+00:00","updated_at":"2023-05-25T00:51:21+00:00","allocated_resources":{"memory":9000,"disk":20480}}}],"meta":{"pagination":{"total":1,"count":1,"per_page":50,"current_page":1,"total_pages":1,"links":{}}}}2023/06/27 09:43:43.993 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m| 582.110058ms|   match|[97;46m POST    [0m /admin-settings   r:/admin-settings
2023/06/27 09:43:44.138 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    334.271µs|   match|[97;44m GET     [0m /static/perfect/css/app-skin.css
2023/06/27 09:43:44.138 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|     71.011µs|   match|[97;44m GET     [0m /static/perfect/css/jquery.tagsinput.css
2023/06/27 09:43:44.139 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|     126.53µs|   match|[97;44m GET     [0m /static/perfect/js/app/app.js
2023/06/27 09:43:44.140 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|     98.483µs|   match|[97;44m GET     [0m /static/perfect/js/jquery.popupoverlay.min.js
2023/06/27 09:43:44.143 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    108.524µs|   match|[97;44m GET     [0m /static/perfect/css/colorbox/colorbox.css
2023/06/27 09:43:44.143 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    265.822µs|   match|[97;44m GET     [0m /static/perfect/css/font-awesome.min.css
2023/06/27 09:43:44.144 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    125.487µs|   match|[97;44m GET     [0m /static/perfect/css/slider.css
2023/06/27 09:43:44.144 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    151.165µs|   match|[97;44m GET     [0m /static/perfect/js/bootstrap-datepicker.min.js
2023/06/27 09:43:44.144 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    406.152µs|   match|[97;44m GET     [0m /static/perfect/bootstrap/css/bootstrap.min.css
2023/06/27 09:43:44.145 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    155.703µs|   match|[97;44m GET     [0m /static/perfect/css/chosen/chosen.min.css
2023/06/27 09:43:44.146 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    108.242µs|   match|[97;44m GET     [0m /static/perfect/css/datepicker.css
2023/06/27 09:43:44.147 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    121.399µs|   match|[97;44m GET     [0m /static/perfect/js/jquery.tagsinput.min.js
2023/06/27 09:43:44.147 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|      94.61µs|   match|[97;44m GET     [0m /static/perfect/js/jquery.slimscroll.min.js
2023/06/27 09:43:44.151 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    127.774µs|   match|[97;44m GET     [0m /static/perfect/js/dropzone.min.js
2023/06/27 09:43:44.152 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|     65.385µs|   match|[97;44m GET     [0m /static/perfect/js/modernizr.min.js
2023/06/27 09:43:44.153 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    306.695µs|   match|[97;44m GET     [0m /static/perfect/js/wysihtml5-0.3.0.min.js
2023/06/27 09:43:44.154 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    206.743µs|   match|[97;44m GET     [0m /static/perfect/js/app/app_form.js
2023/06/27 09:43:44.154 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    345.336µs|   match|[97;44m GET     [0m /static/perfect/js/pace.min.js
2023/06/27 09:43:44.154 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|      70.95µs|   match|[97;44m GET     [0m /static/perfect/css/bootstrap-timepicker.css
2023/06/27 09:43:44.155 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|     128.91µs|   match|[97;44m GET     [0m /static/perfect/css/pace.css
2023/06/27 09:43:44.159 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    200.895µs|   match|[97;44m GET     [0m /static/perfect/css/dropzone/dropzone.css
2023/06/27 09:43:44.159 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    150.402µs|   match|[97;44m GET     [0m /static/perfect/bootstrap/js/bootstrap.min.js
2023/06/27 09:43:44.160 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|     244.33µs|   match|[97;44m GET     [0m /static/perfect/js/chosen.jquery.min.js
2023/06/27 09:43:44.160 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    233.737µs|   match|[97;44m GET     [0m /static/perfect/js/jquery-1.10.2.min.js
2023/06/27 09:43:44.162 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|     71.419µs|   match|[97;44m GET     [0m /static/perfect/js/jquery.maskedinput.min.js
2023/06/27 09:43:44.163 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|     59.843µs|   match|[97;44m GET     [0m /static/perfect/js/jquery.cookie.min.js
2023/06/27 09:43:44.164 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    145.527µs|   match|[97;44m GET     [0m /static/perfect/js/bootstrap-slider.min.js
2023/06/27 09:43:44.165 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    139.599µs|   match|[97;44m GET     [0m /static/perfect/js/jquery.colorbox.min.js
2023/06/27 09:43:44.166 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    163.709µs|   match|[97;44m GET     [0m /static/perfect/js/bootstrap-timepicker.min.js
2023/06/27 09:43:44.168 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|      58.34µs|   match|[97;44m GET     [0m /static/perfect/css/bootstrap-wysihtml5.css
2023/06/27 09:43:44.173 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    163.902µs|   match|[97;44m GET     [0m /static/perfect/js/uncompressed/bootstrap-wysihtml5.js
2023/06/27 09:43:44.193 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|  36.220463ms|   match|[97;44m GET     [0m /static/perfect/css/app.min.css
2023/06/27 09:43:45.651 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|     69.133µs|   match|[97;44m GET     [0m /static/perfect/js/jquery.cookie.min.js
2023/06/27 09:43:45.660 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|    182.922µs|   match|[97;44m GET     [0m /static/perfect/fonts/fontawesome-webfont.woff
2023/06/27 09:43:45.716 [1;44m[D][0m [router.go:1305]  |220.*.*.239|[97;42m 200 [0m|     81.213µs|   match|[97;44m GET     [0m /static/perfect/js/modernizr.min.js`

**Comment by aopkcn** [comment]
这是我的docker-compose.yml
`1`
version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    hostname: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "43306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: PEOMYSQLPASSWORD
      MYSQL_DATABASE: peo
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci

  redis:
    image: redis:alpine
    restart: always
    hostname: redis
    volumes:
# 若要使用持久化redis持久化(append only)功能，则下载 https://github.com/minoic/peo/blob/master/conf/redis.conf
# 到文件夹 ./dist/redis 并将下一行解除注释
#      - ./dist/redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data

  peo:
    image: minoic/peo
    restart: always
    depends_on:
      - redis
      - mysql
    hostname: peo
    volumes:
      - ./conf:/conf
    ports:
      - "8080:8080"
#      - "8088:8088" # 管理员页面，若要开启则解除注释
``

**Comment by aopkcn** [comment]
在配置文件中
alipayenabled = true
开启支付宝成功
smtpenabled = true
smtpencryption = 'SSL'
smtphost = 'smtp.aliyun.com'
smtpport = 465
smtpsendfrom = '**@aliyun.com'
smtpusername = '*@aliyun.com'
smtpuserpassword = '*'

邮件验证正常

目前还是添加商品需要强制清空浏览器缓存才可以显示商品
密钥只能用充值
![image](https://github.com/minoic/peo/assets/45751694/fb7a0a3d-adac-4038-947f-c6fe942f7781)
无论添加那种服务器都购买失败 
![image](https://github.com/minoic/peo/assets/45751694/d17ea44e-b008-4918-ae7e-2ac442692900)

这是购买失败日志
2023/06/27 11:08:58.827 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m| 1.298005419s|   match|[97;44m GET     [0m /order/7/pay-by-balance   r:/order/:orderID/pay-by-balance
2023/06/27 11:09:00.878 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m| 254.458197ms|   match|[97;44m GET     [0m /order/7   r:/order/:orderID
2023/06/27 11:09:01.014 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    168.872µs|   match|[97;44m GET     [0m /static/perfect/css/font-awesome.min.css
2023/06/27 11:09:01.017 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|   8.450924ms|   match|[97;44m GET     [0m /static/perfect/bootstrap/css/bootstrap.min.css
2023/06/27 11:09:01.032 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|  18.337801ms|   match|[97;44m GET     [0m /static/perfect/css/app.min.css
2023/06/27 11:09:01.087 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    185.108µs|   match|[97;44m GET     [0m /static/perfect/css/app-skin.css
2023/06/27 11:09:01.148 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|     81.387µs|   match|[97;44m GET     [0m /static/perfect/css/pace.css
2023/06/27 11:09:01.148 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    121.148µs|   match|[97;44m GET     [0m /static/perfect/css/chosen/chosen.min.css
2023/06/27 11:09:01.175 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    124.822µs|   match|[97;44m GET     [0m /static/perfect/css/datepicker.css
2023/06/27 11:09:01.216 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|     82.801µs|   match|[97;44m GET     [0m /static/perfect/css/bootstrap-timepicker.css
2023/06/27 11:09:01.242 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    178.153µs|   match|[97;44m GET     [0m /static/perfect/css/slider.css
2023/06/27 11:09:01.245 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|      78.92µs|   match|[97;44m GET     [0m /static/perfect/css/jquery.tagsinput.css
2023/06/27 11:09:01.283 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|     86.422µs|   match|[97;44m GET     [0m /static/perfect/css/bootstrap-wysihtml5.css
2023/06/27 11:09:01.312 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    175.658µs|   match|[97;44m GET     [0m /static/perfect/css/dropzone/dropzone.css
2023/06/27 11:09:01.338 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    219.584µs|   match|[97;44m GET     [0m /static/perfect/css/colorbox/colorbox.css
2023/06/27 11:09:01.374 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    295.108µs|   match|[97;44m GET     [0m /static/perfect/js/jquery-1.10.2.min.js
2023/06/27 11:09:01.386 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    237.373µs|   match|[97;44m GET     [0m /static/perfect/bootstrap/js/bootstrap.min.js
2023/06/27 11:09:01.675 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|     77.808µs|   match|[97;44m GET     [0m /static/perfect/js/modernizr.min.js
2023/06/27 11:09:02.220 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    205.234µs|   match|[97;44m GET     [0m /static/perfect/fonts/fontawesome-webfont.woff
2023/06/27 11:09:02.499 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    160.098µs|   match|[97;44m GET     [0m /static/perfect/js/pace.min.js
2023/06/27 11:09:02.565 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    117.624µs|   match|[97;44m GET     [0m /static/perfect/js/jquery.popupoverlay.min.js
2023/06/27 11:09:02.638 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    128.287µs|   match|[97;44m GET     [0m /static/perfect/js/jquery.slimscroll.min.js
2023/06/27 11:09:02.711 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|     69.213µs|   match|[97;44m GET     [0m /static/perfect/js/jquery.cookie.min.js
2023/06/27 11:09:02.714 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|     56.277µs|   match|[97;44m GET     [0m /static/perfect/js/app/app_form.js
2023/06/27 11:09:02.715 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    137.156µs|   match|[97;44m GET     [0m /static/perfect/js/app/app.js
2023/06/27 11:09:02.796 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|     76.463µs|   match|[97;44m GET     [0m /static/perfect/js/jquery.maskedinput.min.js
2023/06/27 11:09:02.799 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    141.853µs|   match|[97;44m GET     [0m /static/perfect/js/chosen.jquery.min.js
2023/06/27 11:09:02.818 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    137.664µs|   match|[97;44m GET     [0m /static/perfect/js/bootstrap-datepicker.min.js
2023/06/27 11:09:02.887 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    170.802µs|   match|[97;44m GET     [0m /static/perfect/js/bootstrap-timepicker.min.js
2023/06/27 11:09:02.896 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    103.783µs|   match|[97;44m GET     [0m /static/perfect/js/jquery.tagsinput.min.js
2023/06/27 11:09:02.897 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    130.458µs|   match|[97;44m GET     [0m /static/perfect/js/bootstrap-slider.min.js
2023/06/27 11:09:02.965 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    230.463µs|   match|[97;44m GET     [0m /static/perfect/js/uncompressed/bootstrap-wysihtml5.js
2023/06/27 11:09:02.967 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    330.597µs|   match|[97;44m GET     [0m /static/perfect/js/wysihtml5-0.3.0.min.js
2023/06/27 11:09:02.967 [1;44m[D][0m [router.go:1305]  |220.166.123.241|[97;42m 200 [0m|    204.569µs|   match|[97;44m GET     [0m /static/perfect/js/dropzone.min.js

**Comment by minoic** [comment]
添加商品未及时显示是由于每分钟刷新一次商品信息，目前已更新至添加商品时立即刷新。
支付宝开关问题和服务器创建问题已与v0.2.5版本修复。
升级可参照 https://github.com/minoic/peo/tree/v0.2.5#%E5%8D%87%E7%BA%A7 。
感谢再次反馈问题。

**Comment by aopkcn** [comment]
> 添加商品未及时显示是由于每分钟刷新一次商品信息，目前已更新至添加商品时立即刷新。 支付宝开关问题和服务器创建问题已与v0.2.5版本修复。 升级可参照 https://github.com/minoic/peo/tree/v0.2.5#%E5%8D%87%E7%BA%A7 。 感谢再次反馈问题。

这次更新能够买创建服务器吗？

**Comment by minoic** [comment]
可以，我这边测试创建正常

**Comment by minoic** [comment]
> ![](https://user-images.githubusercontent.com/45751694/249020954-d17ea44e-b008-4918-ae7e-2ac442692900.png)

CDKey直接购买服务器测试也正常，key和订单的商品类型要一致，或者是和余额支付一样的翼龙面板创建问题。
