### ISSUE TITLE
docker莫名其妙停止后启动失败，需要多次重启才能成功 不知到哪里的问题

### ISSUE THREAD

**Issue by aopkcn** [minoic/peo#22]
`[34m2023-07-08 17:07:20| settings_conf.go:109 | [DEBG]:    Added locale file de-DE.ini to system[39m
[34m2023-07-08 17:07:20| settings_conf.go:109 | [DEBG]:    Added locale file en-US.ini to system[39m
[34m2023-07-08 17:07:20| settings_conf.go:109 | [DEBG]:    Added locale file zh-CN.ini to system[39m
[33m2023-07-08 17:07:20| database_connector.go:40 | [WARN]:    Trying to connect to database![39m
[34m2023-07-08 17:07:23| database_connector.go:28 | [DEBG]:    root:PEOMYSQLPASSWORD@(mysql:3306)/peo?charset=utf8&parseTime=True&loc=Local[39m
2023/07/08 17:07:23.852 [1;44m[D][0m [admin.go:86]  now we don't start tasks here, if you use task module, please invoke task.StartTask, or task will not be executed
2023/07/08 17:07:23.852 [1;34m[I][0m [admin.go:92]  Admin server Running on 0.0.0.0:8088
2023/07/08 17:07:23.853 [1;34m[I][0m [server.go:281]  http server Running on http://0.0.0.0:8088
2023/07/08 17:07:23.855 [1;34m[I][0m [server.go:281]  http server Running on http://:8080
panic: interface conversion: interface {} is nil, not []pterodactyl.Egg

goroutine 83 [running]:
github.com/minoic/peo/internal/controllers.RefreshServerInfo()
	/workspace/internal/controllers/user_console_controller.go:159 +0x1576
github.com/robfig/cron/v3.FuncJob.Run(0x1501778)
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1f
github.com/robfig/cron/v3.(*Cron).startJob.func1()
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0xa8
created by github.com/robfig/cron/v3.(*Cron).startJob
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xc5`

**Comment by aopkcn** [comment]
测试中发现容器重启成功后不访问站点不会停止，但是打开主页后就停止了，出现了 以上错误日志

**Comment by aopkcn** [comment]
数据库日志出现错误
![image](https://github.com/minoic/peo/assets/45751694/c1e6ab71-768d-41a6-b6bf-bab9c32922b7)

**Comment by aopkcn** [comment]
这是我的docker-compose.yml
`version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    hostname: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "43306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "PEOMYSQLPASSWORD"
      MYSQL_DATABASE: "peo"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "68:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "PEOMYSQLPASSWORD"
      UPLOAD_LIMIT: "1G"
  redis:
    image: redis:alpine
    restart: always
    hostname: redis
    volumes:
      - ./dist/redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data

  peo:
    image: minoic/peo
    restart: always
    depends_on:
      - redis
      - mysql
    hostname: peo
    volumes:
      - ./conf:/conf
    ports:
      - "8080:8080"`

**Comment by aopkcn** [comment]
发现问题所在：
之前在测试中创建了服务器，如果手动删除了翼龙面板中本项目使用API创建的服务器 才会导致这个项目停止

**Comment by minoic** [comment]
目前已添加的数据的管理方式还比较原始，后面更新管理页面后会方便一些，崩溃问题会近期修复
