### ISSUE TITLE
发现一个可怕的事情，本项目每秒请求翼龙面板API问题

### ISSUE THREAD

**Issue by aopkcn** [minoic/peo#23]
在所有的项目中都启用的CDN
![image](https://github.com/minoic/peo/assets/45751694/cd57ac41-d911-4167-bb56-dd4f1506e362)
这个请求量太吓人了，在商品中添加了2种游戏服务器 分别4个类型
下面这是翼龙面板的日志
![image](https://github.com/minoic/peo/assets/45751694/b0eeb015-e9b7-49e1-a93e-2a40b7dda20c)
![image](https://github.com/minoic/peo/assets/45751694/99c4baec-f15d-44ef-8600-2b4415deea9c)
平均每秒次次数在4-8次

**Comment by aopkcn** [comment]
![image](https://github.com/minoic/peo/assets/45751694/ae38599e-088a-4593-b87b-55675dc69779)
这个日志是打开本项目站点后显示商品信息中请求翼龙面板nests中的描述信息，由于之前未启用redis，又使用的CDN不缓存规则,现在启用了redis不知道会不会解决这个问题

**Comment by minoic** [comment]
尽量将peo与翼龙面板部署在相同或相邻网络环境下，5QPS的请求量不算太高，但有些重复请求比较多，可以等待带缓存版本的更新解决这个问题。
