### ISSUE TITLE
用户开通显示的服务器在线和离线问题

### ISSUE THREAD

**Issue by aopkcn** [minoic/peo#25]
![image](https://github.com/minoic/peo/assets/45751694/9b83cfa2-b1bd-4060-b24f-a00d86f21d61)
我创建的开通的服务器不是我的世界，是其它游戏服务器  我想知道这个离线和在线是怎么判断的，不应该是判断服务器启用还是停止中吗？还是说这个功能只是我的世界这个游戏的才能用的

**Comment by minoic** [comment]
是的，目前仅支持mc的状态获取

> README.md
> 主要用于 Minecraft 服务器的出售管理，暂不支持其它种类服务器的状态的信息获取
