### ISSUE TITLE
用户购买创建服务器后API请求频繁

### ISSUE THREAD

**Issue by aopkcn** [minoic/peo#28]
添加缓存的版本API频繁改善明显

现测试用户购买创建服务器后API请求变成1分钟3-6次（一个用户只创建了一个服务器，还是用户未访问站点情况下）
![image](https://github.com/minoic/peo/assets/45751694/365eef3a-fbd4-4832-aeea-9f920aa26f8b)

**Comment by minoic** [comment]
后台会定期刷新服务器状态和商品状态，以便用户打开网页立即就能呈现内容，与是否访问站点无关。
若用户打开站点时再获取则会有较大延迟。
