### ISSUE TITLE
二进制启动相关问题

### ISSUE THREAD

**Issue by kabaka9527** [minoic/peo#30]
![Screenshot_20231105_183517_com.server.auditor.ssh.client.png](https://github.com/minoic/peo/assets/142149737/ddf4d08a-662f-44c0-838a-65c51572abbd)
感觉为redis连接问题，因为在安装Redis时要求填写密码，但是配置文件中并没有Redis的密码设置

**Comment by kabaka9527** [comment]
且好像并没有ip端口的配置项

**Comment by minoic** [comment]
是的，目前还不支持配置文件更改redis密码和web端口，后续更新考虑加入
