### ISSUE TITLE
关于成功运行但是无法访问

### ISSUE THREAD

**Issue by FrostMU** [minoic/peo#4]
在已成功运行的情况下
按照提示访问ip:5701却是无法访问的
防火墙等全部已经放行
请问这可能是什么原因造成的？
感谢

**Comment by minoic** [comment]
如果非本地访问请将 `conf/app.conf` 中的 `httpaddr = "localhost"` 改为 `httpaddr = "0.0.0.0"` 或删除该行

**Comment by FrostMU** [comment]
明白了 谢谢
但是还有一点想请教一下
注册和登陆时出现XSRF 验证失败
请问这是因为哪里没有配置正确吗

**Comment by FrostMU** [comment]
> 明白了 谢谢 但是还有一点想请教一下 注册和登陆时出现XSRF 验证失败 请问这是因为哪里没有配置正确吗

尝试在app.conf里把enablexsrf 的值改为false仍然如此，setting.conf也有相关的配置文件吗

**Comment by minoic** [comment]
这个应该是 chrome 浏览器在 ip 访问时不保存 cookies 的原因，尽量用域名来访问就可以了

https://stackoverflow.com/questions/27254013/why-does-the-session-cookie-work-when-serving-from-a-domain-but-not-when-using-a

**Comment by FrostMU** [comment]
似乎可能不是这方面的问题?我测试了IE/FireFox/Chrome无一例外的都是出现了该问题
使用域名访问和IP访问也都尝试了
但仍然显示XSRF验证错误

**Comment by FrostMU** [comment]
试出来了，似乎是SSL的问题，在未开启SSL之前一直错误，但是部署证书并打开SSL就正常了
感谢
